name: Sync to Hugging Face hub

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Add Hugging Face remote
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote remove hf || true
          git remote add hf https://ASR135:${HF_TOKEN}@huggingface.co/spaces/ASR135/movie-recommender-ui

      - name: Rebase on HF Space main
        run: |
          git fetch hf
          git rebase hf/main || git rebase --abort

      - name: Push to Hugging Face Space
        run: |
          git push hf main
